insert into privilege(uuid, name, description, entity_type, created_date_time, last_modified_date_time)
values (uuid_generate_v4(), 'Edit subject type', 'Edit subject type', 'Subject', current_timestamp,
        current_timestamp),
       (uuid_generate_v4(), 'Edit program', 'Edit program', 'Program', current_timestamp,
        current_timestamp),
       (uuid_generate_v4(), 'Edit encounter type', 'Edit encounter type', 'EncounterType',
        current_timestamp, current_timestamp),
       (uuid_generate_v4(), 'Edit form', 'Edit form', 'Form', current_timestamp,
        current_timestamp),
       (uuid_generate_v4(), 'Edit concept', 'Edit concept', 'Concept', current_timestamp,
        current_timestamp),
       (uuid_generate_v4(), 'Edit organisation configuration', 'Edit organisation configuration like filters, languages, etc.,', 'OrganisationConfig', current_timestamp,
        current_timestamp),
       (uuid_generate_v4(), 'Delete organisation configuration', 'Delete organisation configuration like filters, languages, etc.,', 'OrganisationConfig', current_timestamp,
        current_timestamp),
       (uuid_generate_v4(), 'Upload metadata and data', 'Upload metadata and data', 'Bundle', current_timestamp,
        current_timestamp),
       (uuid_generate_v4(), 'Download bundle', 'Download bundle', 'Bundle', current_timestamp,
        current_timestamp),
       (uuid_generate_v4(), 'Edit checklist configuration', 'Edit checklist configuration', 'ChecklistConfig', current_timestamp,
        current_timestamp),
       (uuid_generate_v4(), 'Edit relationship', 'Edit relationship and its types', 'Relationship', current_timestamp,
        current_timestamp),
       (uuid_generate_v4(), 'Edit documentation', 'Edit documentation and video playlist', 'Documentation', current_timestamp,
        current_timestamp),
       (uuid_generate_v4(), 'Edit offline dashboard and report card', 'Edit offline dashboard and report card', 'OfflineView', current_timestamp,
        current_timestamp),
       (uuid_generate_v4(), 'Edit application menu', 'Edit application menu', 'ApplicationMenu', current_timestamp,
        current_timestamp),
       (uuid_generate_v4(), 'Edit extension', 'Edit extension', 'Extension', current_timestamp,
        current_timestamp),
       (uuid_generate_v4(), 'Edit rule failure', 'Edit rule failure', 'RuleFailure', current_timestamp,
        current_timestamp),
       (uuid_generate_v4(), 'Edit location type', 'Edit location type', 'LocationType', current_timestamp,
        current_timestamp),
       (uuid_generate_v4(), 'Edit location', 'Edit location', 'Location', current_timestamp,
        current_timestamp),
       (uuid_generate_v4(), 'Edit catchment', 'Edit catchment', 'Catchment', current_timestamp,
        current_timestamp),
       (uuid_generate_v4(), 'Edit user configuration', 'Edit identifier assignment, subject assignment, task assignment and group assignment', 'User', current_timestamp,
        current_timestamp),
       (uuid_generate_v4(), 'Edit user group', 'Edit user group details', 'UserGroup', current_timestamp,
        current_timestamp),
       (uuid_generate_v4(), 'Edit identifier source', 'Edit identifier source', 'IdentifierSource', current_timestamp,
        current_timestamp),
       (uuid_generate_v4(), 'Edit identifier user assignment', 'Edit identifier user assignment', 'IdentifierUserAssignment', current_timestamp,
        current_timestamp),
       (uuid_generate_v4(), 'Edit task', 'Edit task', 'Task', current_timestamp,
        current_timestamp),
       (uuid_generate_v4(), 'Delete task', 'Delete task', 'Task', current_timestamp,
        current_timestamp);