-- Indexable RLS org policies (avniproject/avni-server#1008)
--
-- The org-scoped RLS policies generated by enable_rls_on_tx_table / enable_rls_on_ref_table used an
-- `organisation_id = (subquery) OR organisation_id IN (subplan)` USING clause. The OR + hashed subplan is
-- not index-pushable, so every org-scoped read full-sequential-scanned the whole cross-org table.
--
-- This migration replaces the USING clause with `organisation_id = ANY (<stable fn>)`, which IS index-pushable
-- against the existing organisation_id btrees, while preserving visibility exactly (own org + org-group members
-- for tx tables; own org + ancestors + org-group members for ref tables). WITH CHECK is unchanged.
--
-- The change is catalog-only (no data scans, no index builds) and runs in one transaction. lock_timeout makes a
-- blocked ACCESS EXCLUSIVE lock fail the migration fast (atomic rollback to the previous, correct policies)
-- instead of queueing the cluster. Run in the normal deploy window (app stopped, no direct-DB ETL/analytics).

SET LOCAL lock_timeout = '10s';

-- 1. Visible-org-id helper functions.
--    STABLE  -> evaluated once at plan time, so the planner can use it as an index bound (VOLATILE would force
--               per-row evaluation and fall back to a seq scan; IMMUTABLE is wrong - it depends on current_user + data).
--    SECURITY INVOKER (default) -> the inner subqueries run with the caller's RLS, exactly like the old policy subqueries.
--    coalesce(..., '{}') is load-bearing: a group db_user has no organisation row, so the first arm is empty;
--               without the coalesce array_agg would return NULL and `= ANY(NULL)` would hide every row.

CREATE OR REPLACE FUNCTION public.rls_visible_org_ids() RETURNS integer[]
    LANGUAGE sql
    STABLE
AS
$$
SELECT coalesce(array_agg(org_id), '{}'::integer[])
FROM (SELECT id AS org_id FROM public.organisation WHERE db_user = current_user
      UNION
      SELECT organisation_id FROM public.organisation_group_organisation) visible_orgs;
$$;
ALTER FUNCTION public.rls_visible_org_ids() OWNER TO openchs;

CREATE OR REPLACE FUNCTION public.rls_visible_org_ids_with_ancestors() RETURNS integer[]
    LANGUAGE sql
    STABLE
AS
$$
SELECT coalesce(array_agg(org_id), '{}'::integer[])
FROM (SELECT id AS org_id FROM public.org_ids
      UNION
      SELECT organisation_id FROM public.organisation_group_organisation) visible_orgs;
$$;
ALTER FUNCTION public.rls_visible_org_ids_with_ancestors() OWNER TO openchs;

-- 2. Re-point the policy helpers at the new index-friendly USING clause. WITH CHECK is unchanged.
--    The target table is schema-qualified (public.%I) so the functions are immune to the "$user" search_path trap
--    (under SET ROLE <org> an unqualified table name resolves to the org's ETL schema, not public).

-- Shared body: the only difference between tx and ref policies is which visible-org-ids function the USING
-- clause calls. Keeping the DROP/CREATE/ENABLE scaffolding, the policy-naming convention and the (unchanged)
-- WITH CHECK clause in one place means tx and ref policies cannot silently diverge. visibleOrgIdsFn is a
-- trusted internal literal (not user input), so interpolating it into the policy expression is safe.
CREATE OR REPLACE FUNCTION enable_rls_on_org_table(tablename text, visibleOrgIdsFn text) RETURNS text
    LANGUAGE plpgsql
AS
$$
DECLARE
    tabl   TEXT := format('public.%I', tablename);
    polisy TEXT := quote_ident(tablename || '_orgs') || ' ON ' || tabl || ' ';
BEGIN
    EXECUTE 'DROP POLICY IF EXISTS ' || polisy;
    EXECUTE 'CREATE POLICY ' || polisy || '
            USING (organisation_id = ANY (' || visibleOrgIdsFn || '()))
            WITH CHECK ((organisation_id = (select id from public.organisation where db_user = current_user)))';
    EXECUTE 'ALTER TABLE ' || tabl || ' ENABLE ROW LEVEL SECURITY';
    RETURN 'CREATED POLICY ' || polisy;
END
$$;
ALTER FUNCTION enable_rls_on_org_table(text, text) OWNER TO openchs;

CREATE OR REPLACE FUNCTION enable_rls_on_ref_table(tablename text) RETURNS text
    LANGUAGE plpgsql
AS
$$
BEGIN
    RETURN enable_rls_on_org_table(tablename, 'public.rls_visible_org_ids_with_ancestors');
END
$$;
ALTER FUNCTION enable_rls_on_ref_table(text) OWNER TO openchs;

CREATE OR REPLACE FUNCTION enable_rls_on_tx_table(tablename text) RETURNS text
    LANGUAGE plpgsql
AS
$$
BEGIN
    RETURN enable_rls_on_org_table(tablename, 'public.rls_visible_org_ids');
END
$$;
ALTER FUNCTION enable_rls_on_tx_table(text) OWNER TO openchs;

-- 3. Re-apply the matching helper to every org-scoped (`*_orgs`) policy that is still on the old shape, driven
--    by the live catalog (the authoritative source - migration-file history has renamed/flip-flopped tables).
--    `pg_temp.v1_398_stale_orgs_policies()` is the SINGLE source of truth shared by the re-application loop and
--    the trailing assertion, so the selection predicate can never drift between them.
--
--    Classification is strict, not a best-effort default: the old ref USING references the `org_ids` view (and
--    never `db_user`); the old tx USING references `organisation.db_user` directly (and never `org_ids`). A
--    policy matching neither is reported as 'unknown' and ABORTS the migration, rather than being silently
--    mis-applied -- a tx table wrongly treated as ref would widen visibility to ancestor orgs (cross-tenant).
--    The NOT LIKE '%rls_visible_org_ids%' filter makes the whole step idempotent (only old-shaped policies match).
--
--    A few tables were renamed without renaming their policy (e.g. `manual_message` still carries
--    `manual_broadcast_message_orgs`). The loop drops the actual policy by its real name first; the helper then
--    (re)creates the canonical `<table>_orgs`. `organisation` / `users` / ETL `*_rls_policy` tables are out of
--    scope and excluded by the `*_orgs` filter.

CREATE OR REPLACE FUNCTION pg_temp.v1_398_stale_orgs_policies()
    RETURNS TABLE (table_name text, policy_name text, kind text)
    LANGUAGE sql
AS
$$
SELECT table_name,
       policy_name,
       CASE
           WHEN qual LIKE '%org_ids%' AND qual NOT LIKE '%db_user%' THEN 'ref'
           WHEN qual LIKE '%db_user%' AND qual NOT LIKE '%org_ids%' THEN 'tx'
           ELSE 'unknown'
       END AS kind
FROM (SELECT c.relname::text                    AS table_name,
             p.polname::text                    AS policy_name,
             pg_get_expr(p.polqual, p.polrelid) AS qual
      FROM pg_policy p
               JOIN pg_class c ON c.oid = p.polrelid
               JOIN pg_namespace n ON n.oid = c.relnamespace
      WHERE n.nspname = 'public'
        AND p.polname LIKE '%\_orgs') candidate
WHERE qual NOT LIKE '%rls_visible_org_ids%';
$$;

DO
$$
    DECLARE
        rec      record;
        unknowns text;
    BEGIN
        SELECT string_agg(policy_name || ' on ' || table_name, ', ')
        INTO unknowns
        FROM pg_temp.v1_398_stale_orgs_policies()
        WHERE kind = 'unknown';
        IF unknowns IS NOT NULL THEN
            RAISE EXCEPTION 'V1_398: cannot classify org-scoped policy(ies) as tx or ref: %', unknowns;
        END IF;

        FOR rec IN SELECT * FROM pg_temp.v1_398_stale_orgs_policies()
            LOOP
                EXECUTE format('DROP POLICY IF EXISTS %I ON public.%I', rec.policy_name, rec.table_name);
                IF rec.kind = 'ref' THEN
                    PERFORM public.enable_rls_on_ref_table(rec.table_name);
                ELSE
                    PERFORM public.enable_rls_on_tx_table(rec.table_name);
                END IF;
            END LOOP;

        -- 4. Trailing assertion (same source of truth): fail the migration (atomic rollback) if any org-scoped
        --    policy is still on the old, non-indexable shape.
        IF EXISTS (SELECT 1 FROM pg_temp.v1_398_stale_orgs_policies()) THEN
            RAISE EXCEPTION 'V1_398: % org-scoped policy(ies) still on the old non-indexable shape',
                (SELECT count(*) FROM pg_temp.v1_398_stale_orgs_policies());
        END IF;
    END
$$;

DROP FUNCTION pg_temp.v1_398_stale_orgs_policies();
